fix commit
Signed-off-by: Sayan Chowdhury <schowdhury@microsoft.com>

diff --git a/az_sig_publish b/az_sig_publish
--- a/az_sig_publish
+++ b/az_sig_publish
@@ -153,14 +153,18 @@ function ensure-resource-group() {
 }
 
 function login() {
+  AZURE_LOGIN_ERR_FILE=$(mktemp)
   echo "Authenticating to Azure using service principal."
   tracestate="$(shopt -po xtrace || true)"
   set +o xtrace
-  if ! az login --service-principal \
-    --username "${AZURE_CLIENT_ID}" \
-    --password "${AZURE_CLIENT_SECRET}" \
-    --tenant "${AZURE_TENANT_ID}" >/dev/null 2>&1; then
-    echo "Azure login failed."
+  az login --service-principal \
+  --username "${AZURE_CLIENT_ID}" \
+  --password "${AZURE_CLIENT_SECRET}" \
+  --tenant "${AZURE_TENANT_ID}" >/dev/null 2>"$AZURE_LOGIN_ERR_FILE"
+  if [[ $? -ne 0 ]]; then
+    echo "Azure login failed. Error:"
+    cat "$AZURE_LOGIN_ERR_FILE"
+    rm -f "$AZURE_LOGIN_ERR_FILE"
     eval "${tracestate}"
     exit 1
   fi
